# Generated by Django 5.1.4 on 2024-12-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcalar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parca',
            name='kategori',
            field=models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'Akıncı'), ('KIZILELMA', 'Kızıl Elma')], max_length=50),
        ),
        migrations.AlterField(
            model_name='parca',
            name='tur',
            field=models.CharField(choices=[('SOLKANAT', 'Sol Kanat'), ('SAGKANAT', 'Sağ Kanat'), ('GOVDE', 'Gövde'), ('KUYRUK', 'Kuyruk'), ('AVIYONIK', 'Aviyonik')], max_length=50),
        ),
    ]
